GET https://www.pixiv.net/ajax/illust/20
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0
Host: www.pixiv.net
Accept: application/json
Referer: https://www.pixiv.net/artworks/20
Cookie: PHPSESSID=85113018_tBGsvUGYAReiq5EG9R0p8opoWeFaszoI